# This is a basic workflow to help you get started with Actions

name: Meu primeiro CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  GrupoTeste:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Primeira tarefa
        run: echo Executando o que solicitei

      # Runs a set of commands using the runners shell
      - name: Segunda tarefa
        run: |
          echo Sefundo comando ex execução
          echo Projeto Teste.
